steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/smartrinse/api-prod:0.1", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/smartrinse/api-prod:0.1"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "api-smartrinse",
        "--image",
        "gcr.io/smartrinse/api-prod:0.1",
        "--platform",
        "managed",
        "--region",
        "asia-southeast2",
        "--add-cloudsql-instances",
        "smartrinse:asia-southeast2:smartrinse-sql",
        "--allow-unauthenticated",
        "--vpc-connector=test-connector"
      ]
